config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :themes

  get "/", to: "posts#index"
  get "/themes/:theme_id/posts", to:"themes#theme_posts_index"

  resources :posts do
    resources :comments
  end

  resources :themes do
    resources :posts, except: [:index]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :theme
  has_many :comments
  has_many :comments, dependent: :destroy
  has_one_attached :header_image
  has_many_attached :uploads

  validates :title, presence: true
  validates :body, presence: true
  validates :body,  length: { minimum: 250 }
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
  has_many :posts       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :add_params, if: :devise_controller?
  protect_from_forgery with: :exception

  protected
    def add_params
      devise_parameter_sanitizer.permit(:sign_up, keys:[:first_name, :last_name])
    end

    # config.relative_url_root = ""
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def show
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
        redirect_to post_path(@post.id)
      else
        @comment
        render '/posts/show'
  end
end

  def update
  end

  def edit
  end

  def delete
  end

  private
  def comment_params
    params.require(:comment).permit(:body).merge(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user! , except: [:index, :show]

  def index
    @posts = Post.order("id DESC").all
    @tech_theme = Theme.find_by(theme_name:"Tecnología")
    @programation_theme = Theme.find_by(theme_name:"Programación")
    @series_theme = Theme.find_by(theme_name:"Series")
    @series_theme = Theme.find_by(theme_name:"Platzi")
  end

  def show
    @comment = Comment.new
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

# @post = Post.find(params[:id])
# @comments = @post.comments.create(params[:comment])
  def create
    @theme = Theme.find(params[:post][:theme_id])
    @post = @theme.posts.new(params_post)
    if @post.save
      redirect_to posts_path, notice: "Tu entrada se ha guardado con exito."
    else
      render :new
    end
  end

  def update
    post = Post.find(params[:id])
    if post.update(params_post)
      redirect_to post_path, notice: "El producto a sido modificado con exito"
    else
      render :edit
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path, notice: "El post fue eliminado con exito"
  end

  private
  def params_post
    params.require(:post).permit(:title, :body, :theme_id, :header_image, uploads:[]).merge(user_id: current_user.id)
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController

  def theme_posts_index
     @theme = Theme.find(params[:theme_id])
     @posts = @theme.posts.order("id DESC").all
     @themes = Theme.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = [:hard_wrap, :filter_html, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode]
    md = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    syntax_highlighter(md.render(text)).html_safe
  end

  def syntax_highlighter(html)
    doc = Nokogiri::HTML(html)
    doc.search("//pre[@lang]").each do |pre|
      pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
    end
    doc.to_s
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def form_title
		@post.new_record? ? "Publica tu post" : "Edita tu post"
	end

	def time(post)
		timeNow = Time.now.strftime("%d/%m/%Y %H:%M")
		timeCreated = post.created_at
		diff = timeNow.to_time.to_i - timeCreated.to_time.to_i
		if diff<3600
			time = diff/60
			"Se posteó hace #{time} mínutos"
		elsif diff < 86400
			time = diff/3600
			"Se posteó hace #{time} horas"
		else
			time = diff/(3600*24)
			"Se posteó hace #{time} días"
		end
	end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/comments/_show.html.erb
<div class="container">
  <div class="row">
    <%=form_for [@post, @post.comments.new] do |f|%>
    <div class="form-group">
      <%=f.text_area :body, class: "form-control input-lg", placeholder:"Ingresa un comentario"%>
    </div>
    <br>
    <%=f.submit "Agrega tu comentario", class: "btn btn-success btn-lg btn-block"%>
    <%end%>
  </div>
</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogueando</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-warning">
      <a class="navbar-brand navbar-name" href="/posts" style="color:#ffffff">Blogueando</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup" style="background-image:url(/assets/person.png);background-size:contain;">
          <div class="title">
            <%if user_signed_in?%>
              <div>
                <a class="nav-item nav-link active say_hi" href="#">¡ Hola <%=current_user.first_name%> <%=current_user.last_name%> !
              </div>
              <div class="">
                <div class="">
                  <a class="nav-item col-sm-offset-10 col-md-offset-8" href="#"><%=link_to "Salir", destroy_user_session_path, :method => 'delete', style:"font-size:20px; color:#ffffff; " ;%></a>
                </div>
                <%else%>
                <div class="col-sm-offset-6 col-md-offset-6">
                  <a class="sign nav-item nav-link" href="#"><%=link_to "Iniciar Sesión", new_user_session_path, style:"font-size:20px;color:#ffffff;"%></a>
                  <a class="signout nav-item nav-link" href="#"><%=link_to "Regístrate", new_user_registration_path, style:"font-size:20px;color:#ffffff;"%></a>
                </div>
              </div>
            </div>
          <%end%>
        </div><!-- Navbar content -->
    </nav>
  <% if flash[:notice] %>
  	<div class="alert alert-info">
  		<%= flash[:notice] %>
  	</div>
  <% end %>
    <%= yield %>
    <footer style="color:white; background-size: contain; background-image:url(/assets/person.png);"> © 2019 <strong> Blogueando </strong>, Todos los Derechos Reservados
     </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container" style="width:70%;margin-top:110px;">
	<div class="row">
		<h1><%= form_title %></h1>
		<% if @post.errors.any? %>
			<div class="alert alert-danger">
				<ul>
				<% @post.errors.full_messages.each do |error|%>
					<li> <%= error  %></li>
				<% end %>
				</ul>
			</div>
		<% end %>
		<br>
		<br>
		<%= form_for @post do |f| %>
			<div class="form_group">
				 <%= f.file_field :header_image, class: "form-control" %>
			</div>
			<div class="btn-group">
				<div class="col-sm-12">
					<%=label_tag(:theme_name, "theme")%>
					<%= f.collection_select :theme_id, Theme.all,:id,:theme_name, {}, class: "form-control"%>
				</div>
			</div>
			<br>
			<div class="form_group">
				<%= f.text_field :title, class: "form-control input-lg title", placeholder:"Título del post"%>
			</div>
			<br>
			<div class="form_group">
				<%= f.text_area :body, class: "form-area form-control input-lg", id:"form-area", placeholder:"Escribe tu entrada"%>
			</div>
			<br>
			<div class="form_group">
				 <%= f.file_field :uploads, multiple: true,  class: "form-control" %>
			</div>
			<br>
			<div>
				<%= f.submit form_title, class: "btn btn-success btn-lg btn-block" %>
			</div>
		<% end %>
	</div>
</div>

app/views/posts/_local.html.erb
<p><%=@post.user.email%>,<%=time(@post)%></p>
  <p><%=markdown(@post.body) %></p>
    <%@post.uploads.each do |upload|%>
      <% if upload.variable?%>
        <%=link_to image_tag(upload.variant(resize: "300x300")), upload%>
        <% elsif upload.previewable?%>
          <%=link_to image_tag(upload.preview(resize: "300x300")), rails_blob_path(upload, disposition: :attachment)%>
        <% elsif upload.image?%>
          <%=link_to image_tag(upload, width: 400), upload%>
        <% else %>
          <%=link_to upload.filename, rails_blob_path(upload, disposition: :attachment)%>
      <% end %>
    <%end%>

app/views/posts/_modal.html.erb
<div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content" style="background-color:gold">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'reason_blog'%>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/posts/_reason_blog.html.erb
<p>Blogueando nace de la sencilla razón de expresar y dar a conocer las cosas que más nos gustan, tiene como objetivo volverse una comunidad de personas que se diviertan escribiendo lo que hacen, lo que han leído, comido etc y que podamos hacer una retroalimentación a eso.</p>

<p>Cosas por decir: </p>

<p> - A medida que van surgiendo nuevos temas se irán agregando los links para agruparlos en categorías</p>

<p> - Todo mensaje irrespetuoso será borrado inmediatamente y dependiendo del comentario se bloqueará al usuario ya que esto es un espacio para divertirnos</p>

<p> - Cualquier duda o sugerencia pueden escribirme a justxtoday@gmail.com</p>



<p>Angie</p>

app/views/posts/_show.html.erb
    <div class="col-md-7 col-md-offset-2 col-sm-12">
      <%=form_for [@post, @post.comments.new] do |f|%>
      <div class="form-group">
        <%=f.text_area :body, class: "form-control input-lg", placeholder:"Ingresa un comentario"%>
      </div>
     <%=f.submit "Agrega tu comentario", class: "btn btn-success btn-lg btn-block"%>
      <%end%>
    </div>

app/views/posts/edit.html.erb
<%= render 'form'  %>

app/views/posts/index.html.erb
<div class="col-md-offset-3 col-sm-offset-2">
  <div class="col-md-offset-9 col-sm-offset-9">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalScrollable">
      Porqué Blogueando?
    </button>
    <!-- /Button trigger modal -->
  </div>

  <%= link_to "Tecnología",theme_posts_path(@tech_theme.id), class: "btn btn-primary" %>
  <%= link_to "Series",theme_posts_path(@series_theme.id), class: "btn btn-primary" %>
  <%= link_to "Programación",theme_posts_path(@programation_theme.id), class: "btn btn-primary" %>
  <%= link_to "Platzi",theme_posts_path(@platzi_theme.id), class: "btn btn-primary" %>

<!-- Modal -->
  <%= render 'modal'%>
<!--  /Modal-->

  <div class="col-md-offset-9 col-sm-offset-9">
    <%= link_to "Crear un nuevo post", new_post_path, class: "btn btn-danger" %>
  </div>
</div>
  <div class="container" style="margin-top:120px;">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
        <%@posts.each do |post|%>
            <div class="col-md-12">
              <a href="/posts/<%=post.id%>"><h1><%= post.title %></h1></a>
              <span class="badge badge-dark">
                <%if%>
                  <% post.theme_id == 1%>
                  <p>Tema: <%= "Tecnología" %></p>
                <%elsif%>
                  <% post.theme_id == 2%>
                  <p>Tema: <%= "Series" %></p>
                <%elsif%>
                  <% post.theme_id == 3%>
                  <p>Tema: <%= "Programación" %></p>
                <%else%>
                  <p>Tema: <%= "Platzi" %></p>
                <%end%>
            </span>
            </div>
              <% if post.header_image.attached? %>
              <div class="col-md-12">
                <!-- <p class="unique"> <%= post.created_at %></p> -->
                <p class="unique"> <strong><%= time(post) %></strong></p>
                <p class="unique"> <strong><%= post.user.first_name%> <%=post.user.last_name%> - <%= post.user.email%></strong></p>
              </div>
              <div class="">
                <div class="col-md-5">
                  <%=image_tag post.header_image.variant(resize: "300x300")%>
                </div>
                <div class="col-md-7 text form-group body-post">
                  <%= markdown(post.body[0..500])%>
                </div>
              </div>
            <% else %>
            <div class="col-md-12">
              <p class="unique"> <%= post.created_at %></p>
              <p class="unique"> <%= time(post) %></p>
              <p class="unique"> Usuario: <%= post.user.email%></p>
            </div>
            <div class="text form-group body-post">
              <p><%= markdown(post.body[0..500])%></p>
            </div>
          <% end %>
            <%if user_signed_in? && current_user.id == post.user.id %>
            <div class="col-md-offset-2">
              <p class="p-index"> <%= link_to "Editar el post", edit_post_path(post.id)%> -
              <%= link_to "Borrar el post", post_path(post.id), method: :delete, data: { confirm: "¿Estás seguro de eliminar este Post?"}%></p>
            </div>
            <%end%>
            <br>
            <hr>
        <%end%>
      </div>
    </div>
  </div>

app/views/posts/new.html.erb
<%= render 'form' %>  

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <%= link_to "Ir a los posts", posts_path, class:"btn-danger btn-lg  col-sm-offset-10", style:"padding:10px;"%>
      <div class="col-md-12">
        <div class="col-md-8 col-md-offset-2">
          <h1 style="color:#337ab7"><%=markdown(@post.title)%></h1>
          <% if @post.header_image.attached? %>
            <p><strong>Creado por:</strong> <%= @post.user.first_name%> <%= @post.user.last_name%> (<%=@post.user.email%>)</p>
            <p style="margin-bottom:20px"></p>
            <p><%=time(@post)%></p>
          <div class="col-md-offset-1 col-sm-offset-1" style="">
          <div >
            <%=image_tag @post.header_image.variant(resize: "500x300")%>
          </div>
          </div>
        </div>
        <div class="col-md-7 col-md-offset-2" style="margin-bottom:50px;margin-top:50px;">
          <div class="" style="margin-bottom:50px;font-size:17px;">
            <p class="post-body-text"><%=markdown(@post.body)%></p>
          </div>
          <% @post.uploads.each do |upload|%>
            <% if upload.variable?%>
                <%=link_to image_tag(upload.variant(resize: "100x100")), upload%>
              <% elsif upload.previewable?%>
              <h5 style="color:blue;">Descarga la Imagen</h5>
                <%=link_to image_tag(upload.preview(resize: "100x100")), rails_blob_path(upload, disposition: :attachment)%>
              <% elsif upload.image?%>
                <%=link_to image_tag(upload, width: 300), upload%>
              <% else %>
                <%=link_to upload.filename, rails_blob_path(upload, disposition: :attachment)%>
            <%end%>
          <%end%>
          <h5 style="color:blue;">Mira los archivos Adjuntos</h5>
        </div>
      </div>
        <% else %>
          <%= render 'local'  %>
        <%end%>

        <%if @comment.errors.any?%>
          <div class="alert alert-danger">
            <ul>
              <% @comment.errors.full_messages.each do |error|%>
                 <li><%= error %></li>
              <%end%>
            </ul>
          </div>

          <%else%>
          <div class="comments col-md-offset-2 col-sm-6">
            <h2>Comentarios</h2>
            <% @post.comments.each do |comment| %>
            <hr>
            <div class="panel panel-default col-md-8">
              <header class="panel-heading"><%= comment.user.email %></header>
              <div class="panel-body"><%= comment.body %></div>
            </div>
          <% end %>
          </div>
        <%end%>
        <%if user_signed_in? %>
          <%= render 'show'  %>
        <%end%>
    </div>
  </div>
</div>

app/views/themes/_themes.html.erb
<div class="col-md-8 col-md-offset-2 col-sm-offset-1">
  <div class="col-md-12">
    <% if @theme.theme_name == "Tecnología"%>
      <div class="btn btn-success"><%=@theme.theme_name%></div>
    <% elsif @theme.theme_name == "Series"%>
      <div class="btn btn-success"><%=@theme.theme_name%></div>
    <% else %>
    <div class="btn btn-success"><%=@theme.theme_name%></div>
    <% end %>
  </div>
</div>

app/views/themes/show.html.erb
<h1>Vista show theme</h1>

app/views/themes/theme_posts_index.html.erb
<div class="col-md-offset-9 col-sm-offset-9">
  <%= link_to " <--- Ir a todos los blogs",posts_path, class: "btn btn-primary" %>
</div>

<br>

<div class="col-md-offset-9 col-sm-offset-9">
  <%= link_to "Crear un nuevo post", new_post_path, class: "btn btn-danger" %>
</div>

<%= render 'themes'%>

<div class="container" style="margin-top:120px;">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
      <%@posts.each do |post|%>
          <div class="col-md-12">
            <a href="/posts/<%=post.id%>"><h1><%= post.title %></h1></a>
            <%if%>
              <% post.theme_id == 1%>
              <p>Tema: <%= "Tecnología" %></p>
            <%elsif%>
              <% post.theme_id == 2%>
              <p>Tema: <%= "Series" %></p>
            <%elsif%>
              <% post.theme_id == 3%>
              <p>Tema: <%= "Platzi" %></p>
            <%else%>
              <p>Tema: <%= "Programación" %></p>
            <%end%>
          </div>
            <% if post.header_image.attached? %>
            <div class="col-md-12">
              <p class="unique"> <%= time(post) %></p>
              <p class="unique"> <%= post.user.first_name%> <%=post.user.last_name%></p>
              <p class="unique" style="margin-bottom:30px;"> <%= post.user.email%></p>
            </div>
            <div class="">
              <div class="col-md-5">
                <%=image_tag post.header_image.variant(resize: "300x300")%>
              </div>
              <div class="col-md-7 text form-group body-post">
                <%= markdown(post.body[0..500])%>
              </div>
            </div>
          <% else %>
          <div class="col-md-12">
            <p class="unique"> <%= post.created_at %></p>
            <p class="unique"> <%= time(post) %></p>
            <p class="unique"> Usuario: <%= post.user.email%></p>
          </div>
          <div class="text form-group body-post">
            <p><%= markdown(post.body[0..500])%></p>
          </div>
        <% end %>
          <%if user_signed_in? && current_user.id == post.user.id %>
          <div class="col-md-offset-2">
            <p class="p-index"> <%= link_to "Editar el post", edit_post_path(post.id)%> -
            <%= link_to "Borrar el post", post_path(post.id), method: :delete, data: { confirm: "¿Estás seguro de eliminar este Post?"}%></p>
          </div>
          <%end%>
          <br>
          <hr>
      <%end%>
    </div>
  </div>
</div>